-- MySQL Script generated by MySQL Workbench
-- Sun Jan 30 18:44:54 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema programmaUniversitario
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `programmaUniversitario` ;

-- -----------------------------------------------------
-- Schema programmaUniversitario
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `programmaUniversitario` ;
SHOW WARNINGS;
USE `programmaUniversitario` ;

-- -----------------------------------------------------
-- Table `Tbl_Corso`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Tbl_Corso` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `Tbl_Corso` (
  `IDCorso` INT NOT NULL AUTO_INCREMENT,
  `CodiceCorso` VARCHAR(255) NULL DEFAULT NULL,
  `Dipartimento` VARCHAR(255) NULL DEFAULT NULL,
  `NomeCorso` VARCHAR(255) NULL DEFAULT NULL,
  `Istituto` VARCHAR(255) NULL DEFAULT NULL,
  `Aula` VARCHAR(255) NULL DEFAULT NULL,
  `GiornateCorso` VARCHAR(255) NULL DEFAULT NULL,
  `OrarioCorso` VARCHAR(255) NULL DEFAULT NULL,
  `DataInizioCorso` DATETIME NULL DEFAULT NULL,
  `DataFineCorso` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`IDCorso`))
ENGINE = myisam
DEFAULT CHARACTER SET = utf8;

SHOW WARNINGS;
CREATE INDEX ON `Tbl_Corso` (`IDCorso` ASC) VISIBLE;

SHOW WARNINGS;
CREATE INDEX ON `Tbl_Corso` (`IDCorso` ASC) VISIBLE;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `Tbl_Iscrizione`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Tbl_Iscrizione` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `Tbl_Iscrizione` (
  `IDIscrizione` INT NOT NULL AUTO_INCREMENT,
  `IDUtente` INT NULL DEFAULT 0,
  `IDCorso` INT NULL DEFAULT 0,
  `DataIscrizione` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`IDIscrizione`))
ENGINE = myisam
DEFAULT CHARACTER SET = utf8;

SHOW WARNINGS;
CREATE INDEX ON `Tbl_Iscrizione` (`IDUtente` ASC) VISIBLE;

SHOW WARNINGS;
CREATE INDEX ON `Tbl_Iscrizione` (`IDUtente` ASC) VISIBLE;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `Tbl_Prova`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Tbl_Prova` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `Tbl_Prova` (
  `IDProva` INT NOT NULL AUTO_INCREMENT,
  `IDIscrizione` INT NULL DEFAULT 0,
  `CodiceProva` VARCHAR(255) NULL DEFAULT NULL,
  `TipoProva` VARCHAR(255) NULL DEFAULT NULL,
  `DataProva` DATETIME NULL DEFAULT NULL,
  `Votazione` INT NULL DEFAULT 0,
  `Lode` TINYINT(1) NULL DEFAULT 0,
  `Documento` LONGBLOB NULL DEFAULT NULL,
  PRIMARY KEY (`IDProva`))
ENGINE = myisam
DEFAULT CHARACTER SET = utf8;

SHOW WARNINGS;
CREATE INDEX ON `Tbl_Prova` (`IDProva` ASC) VISIBLE;

SHOW WARNINGS;
CREATE INDEX ON `Tbl_Prova` (`IDProva` ASC) VISIBLE;

SHOW WARNINGS;
CREATE INDEX ON `Tbl_Prova` (`IDProva` ASC) VISIBLE;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `Tbl_Utente`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Tbl_Utente` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `Tbl_Utente` (
  `IDUtente` INT NOT NULL AUTO_INCREMENT,
  `Nome` VARCHAR(255) NULL DEFAULT NULL,
  `Cognome` VARCHAR(255) NULL DEFAULT NULL,
  `NumeroMatricola` VARCHAR(255) NULL DEFAULT NULL,
  `Indirizzo` VARCHAR(255) NULL DEFAULT NULL,
  `NCivico` VARCHAR(255) NULL DEFAULT NULL,
  `ComuneResidenza` VARCHAR(255) NULL DEFAULT NULL,
  `Provincia` VARCHAR(255) NULL DEFAULT NULL,
  `CAP` INT NULL DEFAULT 0,
  `Ruolo` VARCHAR(255) NULL DEFAULT NULL,
  `Mail` VARCHAR(255) NULL DEFAULT NULL,
  `RecapitoTelefonico` INT NULL DEFAULT 0,
  `PasswordAccesso` VARCHAR(255) NULL DEFAULT NULL,
  `PasswordAccessoConferma` VARCHAR(255) NULL DEFAULT NULL,
  `Tbl_Iscrizione_IDIscrizione` INT NOT NULL,
  PRIMARY KEY (`IDUtente`, `Tbl_Iscrizione_IDIscrizione`))
ENGINE = myisam
DEFAULT CHARACTER SET = utf8;

SHOW WARNINGS;
CREATE UNIQUE INDEX ON `Tbl_Utente` (`IDUtente` ASC) VISIBLE;

SHOW WARNINGS;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
